name: Update ndlsh-tsv.tsv

on:
  schedule:
    - cron: '39 16 * * *'  # 01:39 (JST)

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: r-lib/actions/setup-pandoc@v2
      with:
        pandoc-version: "latest"

    - uses: quarto-dev/quarto-actions/setup@v2
      with:
        version: pre-release

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.4.2'

    - name: install R packages with renv
      uses: r-lib/actions/setup-renv@v2

    - name: Run R script
      run: Rscript data-raw/dl_ndlsh_tsv.R

    - name: Render README
      run: Rscript src/render.R

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update ndlsh-tsv.tsv
        committer: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
        author: Shinya Uryu <r.sh1nya.uryu@gmail.com>
        title: Update ndlsh-tsv.tsv
        body: This is an automated pull request to update `ndlsh-tsv.tsv`.
        branch: daily-update-ndlsh-tsv
        base: main
